server:
  port: 8006

spring:
  application:
    name: payment-service
  cloud:
    consul:
      host: 49.234.222.102
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true