server:
  port: 2003
spring:
  application:
    name: seata-account-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306?seata_account?useSSL=false
    username: root
    password: 123456

logging:
  level:
    io:
      seata: info

feign:
  hystrix:
    enabled: false

mybatis:
  mapper-locations: classpath:mapper/*.xml

seata:
  enable-auto-data-source-proxy: true
  enabled: true
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      application: seata-server
      group: SEATA-GROUP


