server:
  port: 80
spring:
  application:
    name: order-service
  cloud:
    consul:
      port: 8500
      host: 49.234.222.102
      discovery:
        heartbeat:
          enabled: true
        service-name: ${spring.application.name}
